### ISSUE TITLE
Custom AI Agent LLM

### ISSUE THREAD

**Issue by aaron4522** [PittSailbot/Sailbot#55]
NASA released [ROSA](https://github.com/nasa-jpl/rosa), which allows LLMs to interact with ROS2 by executing commands, modifying code, read logs and help with code creation or debugging. Also we can get personalized suggestions by giving the LLM the context of our project and the code we've already written.

Benefits are that it can help us be more productive by resolving roadblocks faster.

## Tasks
- [X] Follow [ROSA](https://github.com/nasa-jpl/rosa)'s README instructions
- [X] Create Azure resource to take LLM queries (we get $100 of free credits)
- [ ] Test demo code
- [ ] Integrate with our sailbot repo

Its new, so documentation isn't great. Currently stuck at trying to test demo code. Running the demo.sh on WSL2 won't work because it needs X11 forwarding (which should be possible to enable). Trying in a Docker or native Linux environment is much more likely to work.

There's also [pre-made custom agents](https://chatgpt.com/g/g-Nd0MsutNu-ros-assistance) already targeting ROS. Difference is that responses won't be personalized and it can't interact directly with ROS.
